version: "3.7"
services:
    app:
      image: node:16.14.0
      working_dir: /usr/src/app
      tty: true
      volumes:
        - ./:/usr/src/app
      command: >
        bash -c "npm install &&
        npm run start"
